/*

  CREATE SEQUENCE sequence
    [INCREMENT BY n]
    [START WITH n]
    [{MAXVALUE n} | NOMAXVALUE]
    [{MINVALUE n} | NOMINVALUE]
    [{CYCLE | NOCYCLE}]
    [{CACHE | NOCACHE}]
    
*/

CREATE SEQUENCE my_sequence
  INCREMENT BY 10
  START WITH 120
  MAXVALUE 9999
  NOCACHE
  NOCYCLE;
  
CREATE TABLE TEST(
  id NUMBER PRIMARY KEY,
  coll NUMBER
);

--NEXTVAL PROXIMO VALOR
--CURRVAL VALOR ATUAL

INSERT INTO TEST VALUES(my_sequence.NEXTVAL,620);

SELECT *FROM TEST;

SELECT my_sequence.CURRVAL FROM DUAL;

ALTER SEQUENCE my_sequence
  INCREMENT BY 20  
  MAXVALUE 9999
  NOCACHE
  NOCYCLE;
  
  DROP SEQUENCE my_sequence;
