/*
Nome: Rafael Ibiapina Matos
RA: 8016047
*/
/*Cuidado com a forma como você definiu as chaves primárias das tabelas.
 Esta forma só funciona no MySQL. Prefira utilizar o formato ANSII que é PRIMARY KEY (COLUNAS)
 e você acrescenta ao final da tabela. Em algumas tabelas você não definiu as chaves estrangeiras.
 Percebi isso, por exemplo na tabela produto.
Você não definiu as chaves estrangeiras das unidades de recebimento e de estoque da tabela produto. 
Você observou que a tabela produto faz relacionamento com a tabela unidade 2 (DUAS) vezes?
 Quando uma tabela faz relacionamento com a mesma tabela mais de uma vez,
 a chave estrangeira não pode ter o mesmo nome, assim, unidReceb e unidEstoque são as chaves estrangeiras dos relacionamentos com Unidade.
Semana retrasada eu enviei uma mensagem no Correio explicando isso.
Desta forma, por favor, faça as correções e poste novamente até o dia 25/04/2016.*/
CREATE TABLE CLIENTE(
	IDCLIENTE INT(11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	ENDERECO VARCHAR(30),
	DATACADASTRO DATETIME,
	CEP VARCHAR(8),
	DDD VARCHAR(2),
	FONE VARCHAR(8),
	IDBAIRRO INT(11),
	IDSETOR INT (11),
	SITUACAO CHAR(1),
	FOREIGN KEY (IDBAIRRO) REFERENCES BAIRRO(IDBAIRRO),
	FOREIGN KEY (IDSETOR) REFERENCES SETOR(IDSETOR),
	PRIMARY KEY (IDCLIENTE)
);


CREATE TABLE PRODUTO(
	IDPRODUTO INT (11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	PRECOVENDA DECIMAL(9,2) NOT NULL,
	ESTOQUEATUAL INT(11),
	ESTOQUEMINIMO INT(11),
	ESTOQUEMAXIMO INT(11),
	PONTOPEDIDO INT(11),
	DEMANDA INT(11),
	FATORSEGURANCA DECIMAL(5,2),
	CUSTOMEDIO DECIMAL(9,2),
	FATORCONVERSAO DECIMAL(5,2),
	TPOMEDIOREPOS INT(11),
	UNIDESTOQUE INT(11),
	UNIDRECEB INT(11),
	IDGRUPO INT(11),
	FOREIGN KEY (UNIDESTOQUE) REFERENCES UNIDADE(IDUNIDADE),
	FOREIGN KEY (UNIDRECEB) REFERENCES UNIDADE(IDUNIDADE),
	FOREIGN KEY (IDGRUPO) REFERENCES GRUPO(IDGRUPO),
	PRIMARY KEY(IDPRODUTO)
);


CREATE TABLE FORNECEDOR (
	IDFORNECEDOR INT(11) NOT NULL AUTO_INCREMENT ,
	NOME VARCHAR(30) NOT NULL,
	ENDERECO VARCHAR(30),
	DATACADASTRO TIMESTAMP,
	CEP VARCHAR(8),
	DDD VARCHAR(2),
	FONE VARCHAR(8),
	IDBAIRRO INT(11),
	FOREIGN KEY (IDBAIRRO) REFERENCES BAIRRO(IDBAIRRO),
	PRIMARY KEY(IDFORNECEDOR)
);


CREATE TABLE PRODUTOFORN(
	IDFORNECEDOR INT(11),
	IDPRODUTO INT(11),
	PRECOCOMPRA DECIMAL(9,2),
	TAXAREPOSICAO INT(11),
	CONFIABILIDADE VARCHAR(1),
	DESCONTO DECIMAL(5,2),
	FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR),
	FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);


CREATE TABLE COMPRA(
	IDCOMPRA INT(11) NOT NULL AUTO_INCREMENT,
	DATACOMPRA DATETIME NOT NULL,
	IDFORNECEDOR INT (11),
	FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR),
	PRIMARY KEY(IDCOMPRA)
);


CREATE TABLE PRAZOPGTOPA(
	IDCOMPRA INT(11),
	DIASPGTO INT(11),
	FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA(IDCOMPRA)
);


CREATE TABLE PRODUTOCPA(
	IDCOMPRA INT(11),
	IDPRODUTO INT(11),
	QTDE INT(11),
	PRECO DECIMAL(9,2),
	FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA(IDCOMPRA),
	FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);


CREATE TABLE VENDA(
	IDVENDA INT(11) NOT NULL AUTO_INCREMENT,
	DATAVENDA DATETIME NOT NULL,
	IDFUNCIONARIO INT(11),
	IDCLIENTE INT(11),
	FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO),
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
	PRIMARY KEY(IDVENDA)
);


CREATE TABLE PRODUTOVDA(
	IDVENDA INT(11),
	IDPRODUTO INT(11),
	QTDE INT(11),
	PRECO DECIMAL(9,2),
	VLRCOMISSAO DECIMAL(9,2),
	FOREIGN KEY (IDVENDA) REFERENCES VENDA(IDVENDA),
	FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);


CREATE TABLE PRAZOPGTVDA(
	IDVENDA INT(11),
	DIASPGTO INT(11),
	FOREIGN KEY (IDVENDA) REFERENCES VENDA(IDVENDA)
);


CREATE TABLE NOTAFISCAL(
	NUMERO INT(11),
	SERIENFF VARCHAR(10),
	DATAFATURAMENTO DATETIME,
	DATAEMISSAO DATETIME,
	IDVENDA INT,
	FOREIGN KEY (IDVENDA) REFERENCES VENDA(IDVENDA),
	PRIMARY KEY(NUMERO)
	
);


CREATE TABLE SETOR(
	IDSETOR INT(11) NOT NULL AUTO_INCREMENT ,
	DESCRICAO VARCHAR(30),
	PRIMARY KEY(IDSETOR)
);


CREATE TABLE PERIODO(
	IDPERIODO INT(11) NOT NULL AUTO_INCREMENT ,
	DATAINICIO DATETIME,
	DATAFIM DATETIME,
	PRIMARY KEY(IDPERIODO)
);

CREATE TABLE COTASETOR(
	IDSETOR INT(11),
	IDPERIODO INT(11),
	VALOR DECIMAL(9,2),
	FOREIGN KEY (IDSETOR) REFERENCES SETOR(IDSETOR),
	FOREIGN KEY (IDPERIODO) REFERENCES PERIODO(IDPERIODO)
);


CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT(11) NOT NULL AUTO_INCREMENT ,
	NOME VARCHAR(30) NOT NULL,
	ENDERECO VARCHAR(30),
	DATACADASTRO DATETIME,
	DATAADMISSAO DATETIME,
	DATADEMISSAO DATETIME,
	CEP VARCHAR(8),
	DDD VARCHAR(2),
	FONE VARCHAR(8),
	IDBAIRRO INT(11),
	IDSETOR INT(11),
	IDCARGO INT(11),
	FOREIGN KEY (IDBAIRRO) REFERENCES BAIRRO(IDBAIRRO),
	FOREIGN KEY(IDSETOR) REFERENCES SETOR(IDSETOR),
	FOREIGN KEY (IDCARGO) REFERENCES CARGO(IDCARGO),
	PRIMARY KEY(IDFUNCIONARIO)
);


CREATE TABLE VENDEDOR (
	IDFUNCIONARIO INT(11),
	PERCOMISSAO DECIMAL(5,2),
	PLACA VARCHAR(7),
	IDSETOR INT(11),
	FOREIGN KEY (IDSETOR) REFERENCES SETOR(IDSETOR),
	FOREIGN KEY(IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
);


CREATE TABLE CARGO(
	IDCARGO INT(11) NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(30),
	SALARIO DECIMAL(9,2),
	PRIMARY KEY(IDCARGO)
);


CREATE TABLE LOGPRODUTO(
	IDLOGPRODUTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRECOVENDA DECIMAL(9,2),
	ESTOQUEATUAL INT,
	ESTOQUEMINIMO INT,
	ESTOQUEMAXIMO INT,
	PONROPEDIDO INT,
	DEMANDA INT,
	FATORSEGURANCA DECIMAL(5,2),
	CUSTOMEDIO DECIMAL(9,2),
	FATORCONVERSAO DECIMAL(5,2),
	TPOMEDIOREPOS INT,
	UNIDESTOQUE INT(11),
	UNIDRECEB INT (11),
	IDGRUPO INT(11),
	IDPRODUTO INT(11),
	DTA_HOR_LOG DATETIME,
	USUARIO VARCHAR(30),
	FOREIGN KEY (UNIDESTOQUE) REFERENCES UNIDADE(IDUNIDADE),
	FOREIGN KEY (UNIDRECEB) REFERENCES UNIDADE(IDUNIDADE),
	FOREIGN KEY (IDGRUPO) REFERENCES GRUPO(IDGRUPO),
	FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO),
	PRIMARY KEY(IDLOGPRODUTO)
);


CREATE TABLE UNIDADE(
	IDUNIDADE INT(11) NOT NULL AUTO_INCREMENT ,
	SIGLA VARCHAR(5),
	DESCRICAO VARCHAR(30),
	PRIMARY KEY(IDUNIDADE)
);


CREATE TABLE GRUPO(
	IDGRUPO INT(11) NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(30),
	IDTIPO INT(11),
	FOREIGN KEY (IDTIPO) REFERENCES TIPO(IDTIPO),
	PRIMARY KEY(IDGRUPO)
);


CREATE TABLE TIPO(
	IDTIPO INT(11) NOT NULL AUTO_INCREMENT ,
	DESCRICAO VARCHAR(30),
	IDAREA INT(11),
	FOREIGN KEY (IDAREA) REFERENCES AREA(IDAREA),
	PRIMARY KEY (IDTIPO)
);


CREATE TABLE AREA(
	IDAREA INT(11) NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(30),
	PRIMARY KEY(IDAREA)
);


CREATE TABLE TITULO(
	IDTITULO INT(11) NOT NULL AUTO_INCREMENT ,
	HISTORICO VARCHAR(100),
	DATAVENCIMENTO TIMESTAMP,
	VALOR DECIMAL(9,2),
	MOVIMENTO VARCHAR(1),
	PRIMARY KEY(TITULO)
);


CREATE TABLE RECEBER(
	IDTITULO INT(11),
	DATARECEBIMENTO TIMESTAMP,
	ACRESCIMO DECIMAL(9,2),
	DESCONTO DECIMAL(9,2),
	VALORPAGO DECIMAL(9,2),
	IDVENDA INT(11),
	FOREIGN KEY (IDVENDA) REFERENCES VENDA(IDVENDA),
	FOREIGN KEY (IDTITULO) REFERENCES TITULO(IDTITULO)
);


CREATE TABLE PAGAR(
	IDTITULO INT(11),
	DATAPAGAMENTO DATETIME,
	ACRESCIMO DECIMAL(9,2),
	DESCONTO DECIMAL(9,2),
	VALORPAGO DECIMAL(9,2),
	IDCOMPRA INT(11),
	FOREIGN KEY(IDCOMPRA) REFERENCES COMPRA(IDCOMPRA),
	FOREIGN KEY (IDTITULO) REFERENCES TITULO(IDTITULO)
);


CREATE TABLE ESTADO(
	SIGLA VARCHAR(2) NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	PRIMARY KEY(SIGLA)
);


CREATE TABLE CIDADE(
	IDCIDADE INT(11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SIGLA VARCHAR(2),
	PRIMARY KEY(IDCIDADE)
);


CREATE TABLE BAIRRO(
	IDBAIRRO INT(11) NOT NULL AUTO_INCREMENT ,
	NOME VARCHAR(30) NOT NULL,
	REGIÃO VARCHAR(20),
	IDCIDADE INT(11),
	FOREIGN KEY (IDCIDADE) REFERENCES CIDADE(IDCIDADE),
	PRIMARY KEY(BAIRRO)
);


CREATE TABLE MARCA(
	IDMARCA INT(11) NOT NULL AUTO_INCREMENT ,
	DESCRICAO VARCHAR(30),
	PRIMARY KEY(IDMARCA)
);


CREATE TABLE MODELO(
	IDMODELO INT(11) NOT NULL AUTO_INCREMENT ,
	DESCRICAO VARCHAR(30),
	IDMARCA INT(11),
	FOREIGN KEY (IDMARCA) REFERENCES MARCA(IDMARCA),
	PRIMARY KEY(IDMODELO)
);


CREATE TABLE VEICULO(
	PLACA VARCHAR(7) NOT NULL ,
	COR VARCHAR(15),
	ANO YEAR,
	DATACOMPRA DATETIME,
	DATAVENDA DATETIME,
	KM INT(11),
	IDMODELO INT(11),
	FOREIGN KEY(IDMODELO) REFERENCES MODELO(IDMODELO),
	PRIMARY KEY(PLACA)
);


CREATE TABLE VEICULO_USADO_VENDEDOR (
	SEQ_VEICULO_USADO_VENDEDOR INT NOT NULL ,
	IDFUNCIONARIO INT(11),
	PLACA VARCHAR(7),
	DTA_INICIO_UTILIZACAO DATETIME,
	DTA_FIM_UTILIZACAO DATETIME,
	KM_INICIAL INT,
	KM_FINAL INT,
	DSC_OCORRENCIAS VARCHAR(2000),
	FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
	PRIMARY KEY(SEQ_VEICULO_USADO_VENDEDOR)
);
